baseURL: "https://tanmaychimurkar.github.io"
title: Tanmay's Blog
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Categories
                  url: categories
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 11
                - name: Search
                  url: search/
                  weight: 12

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    googleAnalytics: "UA-XXXXX-X"
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Me
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    ShowWordCount: false
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false

    homeInfoParams:
        Title: "Hi There 👋"
        Content: >
            Welcome to my corner on the Internet. Here I write about things that I find useful in my everyday 
            software workflow, and more importantly about things that I tend to forget!
            
    socialIcons:
        - name: github
          url: "https://github.com/tanmaychimurkar"
        - name: Linkedin
          url: "https://www.linkedin.com/in/chimurkartanmay/"
        - name: Medium
          url: "https://medium.com/@chimurkar.tanmay"
        - name: Xing
          url: "https://www.xing.com/profile/Tanmay_Chimurkar/cv"

    editPost:
        URL: "https://github.com/tanmaychimurkar/tanmaychimurkar.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    assets:
        disableHLJS: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/apple-touch-icon.png"

    analytics:
        google:
            SiteVerificationTag: "TKI2D0Wu7RG5sp0Kc0eB1WxxMdTjGdf4iGzsl7OE4jU"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
